import type { Metadata } from "next";
import "./globals.css";
import { TopNav } from "./components/layout/TopNav";
import { Main } from "./components/layout/Main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        <Main>{children}</Main>
      </body>
    </html>
  );
}
