export const Seed = {
  comments: [
    {
      id: "1",
      author: "Alice",
      text: "Great job on the new feature release! Everything looks smooth.",
      date: "2025-05-14T10:00:00Z",
      likes: 12,
      image: "https://randomuser.me/api/portraits/women/1.jpg",
      parentId: null,
    },
    {
      id: "2",
      author: "Bob",
      text: "I found a bug in the upload section. Let me know if I can help.",
      date: "2025-05-14T10:05:00Z",
      likes: 5,
      image: "",
      parentId: null,
    },
    {
      id: "3",
      author: "Charlie",
      text: "This update really improved performance. Thanks for listening to user feedback!",
      date: "2025-05-14T10:15:00Z",
      likes: 18,
      image: "https://randomuser.me/api/portraits/men/3.jpg",
      parentId: null,
    },
    {
      id: "4",
      author: "Admin",
      text: "Thanks for the feedback, everyone! We’ll be shipping more fixes soon.",
      date: "2025-05-14T10:30:00Z",
      likes: 22,
      image: "",
      parentId: null,
    },
    {
      id: "5",
      author: "Dana",
      text: "Can we get dark mode support next?",
      date: "2025-05-14T10:45:00Z",
      likes: 9,
      image: "https://randomuser.me/api/portraits/women/5.jpg",
      parentId: null,
    },
    {
      id: "6",
      author: "Admin",
      text: "We’re working on dark mode now. Stay tuned!",
      date: "2025-05-14T11:00:00Z",
      likes: 4,
      image: "",
      parentId: "5",
    },
    {
      id: "7",
      author: "Eve",
      text: "Glad to hear performance is better now.",
      date: "2025-05-14T11:10:00Z",
      likes: 6,
      image: "https://randomuser.me/api/portraits/women/7.jpg",
      parentId: "3",
    },
  ],
};
